### PR TITLE
Chrome extension feature added

### PR DESCRIPTION
**Pull request by AtharvaThorve**
Since there are many pull requests regarding the URL handling part of the project I decided to make a chrome extension to inject features of the project starfish to the GitHub website.

Currently, as the app is not yet been created I just made a chrome extension(going to work on other browsers later). This extension gets activated on Github only.
This is not a final submission of the extension, it is to get an idea of what more features that must be added. 

Currently, the extension gives the user a choice to clone the repository and open it in a specific IDE.
On clicking the option of Open in starfish the extension would open the starfish app. Right now the functionality is not included as the main goal of this pull request was to get a much deeper idea of how the extension should work.
The extension also allows the user to view the URLs and the features that were previously selected.

View the [Readme](https://github.com/AtharvaThorve/starfish/blob/master/Chrome%20Extension/README.md) on how to set up the extension and use it.

### CODE REVIEW

**Comment by maxandersen** [comment]
very nice! Having the actions as a menu in the icons is nice and non-invasive. Very good start!

for github and gitlab we might want to do something like https://github.com/gitpod-io/browser-extension where they based on the site adds buttons in relevant places.

**Comment by AtharvaThorve** [comment]
Yes okay, I'll go through it and try to implement something similar to that.

**Comment by AtharvaThorve** [comment]
I'm a bit confused should I directly pick up the code from the repo  https://github.com/gitpod-io/browser-extension and make necessary changes or completely make it from scratch taking the repo as just a reference?

**Comment by maxandersen** [comment]
There is no clear license info in their repo so can't just directly pick up the code.

**Comment by AtharvaThorve** [comment]
Heyy Max, I was thinking of using ReactJS as injecting scripts using that is much easier and I am facing a lot of issues using this way.
Also, I have a good grip on ReactJS so I can work on it more efficiently.

**Comment by AtharvaThorve** [comment]
In the latest commit, I made an extension using ReactJs which made it easier to injecting scripts in the DOM. The UI and functionality are still not up to the mark and I would definitely work on it. 
But this extension works on Google Chrome, Mozilla Firefox, and Microsoft Edge.
I was not able to work on this as much as I want to as I am a bit preoccupied with my college submissions and assignments but would still keep on contributing to improving the code.

**Comment by AtharvaThorve** [comment]
I've made a lot of UI improvements to the extension made using React which can be viewed [here](https://github.com/AtharvaThorve/starfish/tree/master/Extension%20using%20React).
After the latest UI improvement, the extension looks like this<br>
React-Extension

**Comment by maxandersen** [comment]
interesting, but why would the select an IDE be chosen here ? wouldn't that be more natural to have be something starfish can show/open ?

**Comment by maxandersen** [comment]
or as a setting of the extension it self ?

**Comment by AtharvaThorve** [comment]
Ohh okay got it, thank you for the feedback @maxandersen. I'll make the necessary changes

**Comment by AtharvaThorve** [comment]
Heyy @maxandersen, I'm sorry I'm not able to contribute to this project as much as I want to cause I'm a bit caught up with my university assignments and projects. As soon as all of that is done I'll start focusing all my attention on this project.
Thanks and Regards @AtharvaThorve

**Pull request closed without merging**
